spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=fin01
spring.datasource.password=fin01

mybatis.mapper-locations=classpath:com/example/demo/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.dto
mybatis.configuration.map-underscore-to-camel-case=true

server.servlet.encoding.force-response=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=cr2amshop
spring.mail.password=cr2amshop1111
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtps.checkserveridentity=true
spring.mail.properties.mail.smtps.ssl.trust=*
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.location=C:\\springboot\\CR2AM\\src\\main\\resources\\static\\files
